# Generated by Django 5.0.1 on 2024-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['dish_type', 'name', 'price']},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cook',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
