# Generated by Django 5.0.1 on 2024-02-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_dish_options_alter_dishtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
